[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pblade"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gl = { version = "^0.14" }
glfw = { version = "^0.55", default-features = false }
egui = { version = "^0.27" }
egui_gl_glfw = { path = "../egui_gl_glfw/", default-features = false }
cgmath = { version = "^0.18", features = ["swizzle"] }
rand = "^0.7"

[features]
#default = ["wayland", "x11"]
wayland = ["egui_gl_glfw/wayland", "glfw/glfw-sys", "glfw/wayland"]
x11 = []
