[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pblade"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cgmath = { version = "^0.18", features = ["swizzle"] }
rand = "^0.7"
test-case = "3.3.1"
three-d = { version = "^0.17", default-features = false, features = [
	"window",
	"egui-gui",
] }

[profile.release]
debug = true
