[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.0", features = [
	"derive",
	"zeroable_maybe_uninit",
	"zeroable_atomics",
] }
iced = { version = "0.12.0", features = ["debug", "advanced", "svg"] }
iced_aw = { version = "0.9.2", default-features = false, features = [
	"color_picker",
	"card",
	"modal",
	"menu",
	"quad",
	"icons",
] }
image = { version = "0.24.9" }
rand = "^0.8.5"
# Enum iteration
strum = "0.26.2"
strum_macros = "0.26.2"
# Vector and Matrix math
ultraviolet = { version = "0.9.2", features = ["bytemuck"] }

[dev-dependencies]
test-case = { version = "^3.3.0" }

[profile.release]
debug = true
