[package]
name = "polyblade"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.25", features = ["bytemuck"] }
bytemuck = { version = "1.0", features = [
	"derive",
	"zeroable_maybe_uninit",
	"zeroable_atomics",
] }
iced = { version = "0.12.0", features = ["debug", "advanced"] }
iced_aw = { version = "0.8.0", default-features = false, features = [
	"color_picker",
] }
image = { version = "0.24.9" }
rand = "^0.8.5"


[dev-dependencies]
test-case = { version = "^3.3.0" }

[profile.release]
debug = true
