name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
    with:
      cache_version: v1
